#include "JSONDescription.h"

const char TemplateJSON[] = "[{\n"
"	'param' : 'Uset',\n"
"	'type' : 'set',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '1',\n"
"			'unitsMultiply' : '1'\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"},\n"
"{\n"
"	'param' : 'Imeas',\n"
"	'type' : 'measure',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '2',\n"
"			'unitsMultiply' : '1000'\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '3',\n"
"			'unitsMultiply' : '10000',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '4',\n"
"			'unitsMultiply' : '100000',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '5',\n"
"			'unitsMultiply' : '1e6',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '6',\n"
"			'unitsMultiply' : '1e7',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '7',\n"
"			'unitsMultiply' : '1e8',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '8',\n"
"			'unitsMultiply' : '1e9',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '9',\n"
"			'unitsMultiply' : '1e9',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"}]";

float UsetMin, UsetMax, Imeas1Min, Imeas1Max, Imeas2Min, Imeas2Max, Imeas3Min, Imeas3Max;
float Imeas4Min, Imeas4Max, Imeas5Min, Imeas5Max, Imeas6Min, Imeas6Max, Imeas7Min, Imeas7Max, Imeas0Min, Imeas0Max;
