#include "JSONDescription.h"

const char TemplateJSON[] = "[{\n"
"	'param' : 'Uset',\n"
"	'type' : 'set',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '1',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"},\n"
"{\n"
"	'param' : 'Imeas',\n"
"	'type' : 'measure',\n"
"	'ranges': [\n"
"		{\n"
"			'rangeId' : '2',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '3',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '4',\n"
"			'unitsMultiply' : '1',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '5',\n"
"			'unitsMultiply' : '1000',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		},\n"
"		{\n"
"			'rangeId' : '6',\n"
"			'unitsMultiply' : '1000',\n"
"			'active' : '1',\n"
"			'min': '$',\n"
"			'max': '$'\n"
"		}]\n"
"}]";

float UsetMin, UsetMax;
float Imeas0Min, Imeas0Max;
float Imeas1Min, Imeas1Max;
float Imeas2Min, Imeas2Max;
float Imeas3Min, Imeas3Max;
float Imeas4Min, Imeas4Max;
